### ISSUE TITLE
Not working with Entries field

### ISSUE THREAD

**Issue by geertjanknapen1** [goldnead/statamic-collapse-fieldtype#5]
The field does not work when I nest an `Entries` field type inside of it. It throws JS console errors (the same one multiple times).

Now I'm no expert, but it seems that Statamic can no longer 'find' the items I linked in the Entries field, maybe because they are nested in the Collapse field?

Is this a known issue or perhaps intended behavior or a bug?

The console error:
```
TypeError: Cannot read properties of undefined (reading 'map')
    at a.items (RelationshipInput.vue:155:1)
    at fn.get (vue.common.prod.js:6:26596)
    at fn.evaluate (vue.common.prod.js:6:27746)
    at a.items (vue.common.prod.js:6:29650)
    at a.<anonymous> (RelationshipInput.vue:1:180)
    at e._render (vue.common.prod.js:6:35309)
    at a.r (vue.common.prod.js:6:67998)
    at fn.get (vue.common.prod.js:6:26596)
    at fn.run (vue.common.prod.js:6:27480)
    at cn (vue.common.prod.js:6:25588)
```

**Comment by goldnead** [comment]
Thanks, I will check it out.
This might be related to #1
